---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: meanstackmongodbexpressjsangularnodejslnlk
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: REGISTRY_URL/replace-me-namespace/meanstackmongodbexpressjsangularnodejslnlk
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
